Sprint1
ClevertecFrontendLab/sprint1-p121s pull request #1
Opened 2023-02-01 12:57 UTC by p121s

2023-02-01 13:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 6.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256420/content-window.png)

2023-02-01 13:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675256742/content-window.png)

2023-02-01 13:18 UTC, klichkovskiy requested changes

2023-02-01 13:18 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +import React, { useEffect, useState } from 'react';
React не нужно импортировать каждый раз

2023-02-01 13:18 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +          <S.BoldText>Рейтинг</S.BoldText>
![image](https://user-images.githubusercontent.com/62481116/216053736-1effccf8-4b92-4895-b6f6-3b85cc9f5530.png)
Исправь по всему приложению

2023-02-01 13:18 UTC, klichkovskiy commented on src/shared/sort-button/sort-button.component.tsx
> +        <S.Button type='button'><span>По рейтенгу</span></S.Button>
![image](https://user-images.githubusercontent.com/62481116/216053849-3415f903-b319-47e7-860d-d18c182d6f54.png)
рейтингу

2023-02-02 06:26 UTC, p121s commented on src/pages/book/book-page.tsx
> +import React, { useEffect, useState } from 'react';
Да, я об этом знаю. Но Eslint просит вместо <></> вставлять React.Fragment, а для этого нужен React.

2023-02-02 06:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/p121s/1675319354/content-window.png)

2023-02-02 07:01 UTC, klichkovskiy approved these changes

2023-02-02 07:02 UTC, merged